version: '3.8'

services:
  bookstore-db:
    image: postgres:15
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: bookstore
    ports:
      - "5433:5432"
    volumes:
      - bookstore-db-data:/var/lib/postgresql/data

volumes:
  bookstore-db-data:
