version: '3.8'

services:
  drugstore-db:
    image: postgres:15
    environment:
      POSTGRES_DB: drugstore
      POSTGRES_USER: drugstore
      POSTGRES_PASSWORD: drugstore
    ports:
      - "5435:5432"
    volumes:
      - drugstore-db-data:/var/lib/postgresql/data

volumes:
  drugstore-db-data:
